### ISSUE TITLE
Visualizing kraken2+bracken results

### ISSUE THREAD

**Issue by bglindner** [blindner6/CEE6720_BIO6720#6]
Hey all,

Our recommended way for visualizing the kraken results would be with the script found here: https://github.com/rotheconrad/Kraken-Bracken-plot/tree/main

`Kraken-Bracken-plot.py` 

You need to prepare a manifest according to the help documentation. So for example, for the `-k` option that would look like:
```
2010-summer.report.k2   2010-summer
2010-winter.report.k2   2010-winter
...
```
And for the `-i` option that looks like:
```
2010-summer_bracken_classes.br     2010-summer
2010-winter_bracken_classes.br     2010-winter
...
```
If you set the output to `-o kraken_plots.pdf` and download it to your local workspace you should have some nice stacked barplots. Comment below if you have any difficulties!

**Comment by bglindner** [comment]
PS. If you get an error about `pandas`, make sure you have your environment open (i.e., `micromamba activate ./env`). If the error persists, call `micromamba install pandas` and try again.

**Comment by madisonflucas** [comment]
When running this script, I get the following error 
```
Traceback (most recent call last):
  File "/storage/ice1/5/6/mlucas46/lab02/Kraken-Bracken-plot.py", line 474, in <module>
    main()
  File "/storage/ice1/5/6/mlucas46/lab02/Kraken-Bracken-plot.py", line 463, in main
    df, unclassified = parse_bracken(infile, krakenfile)
  File "/storage/ice1/5/6/mlucas46/lab02/Kraken-Bracken-plot.py", line 169, in parse_bracken
    file_lookup, smpl_order = parse_infile(infile)
  File "/storage/ice1/5/6/mlucas46/lab02/Kraken-Bracken-plot.py", line 133, in parse_infile
    samplename = X[1]
IndexError: list index out of range
```
I'm running the script with the command
```
python Kraken-Bracken-plot.py -k kraken_manifest.txt -i class_manifest.txt -o class_kraken_plots.pdf
```
Attached are screenshots of my input text files. 

<img width="573" alt="Screenshot 2024-03-13 at 1 31 27 AM" src="https://github.com/blindner6/CEE6720_BIO6720/assets/144811435/42379e22-1985-414e-b2d7-df1fba43c9e6">
<img width="404" alt="Screenshot 2024-03-13 at 1 31 44 AM" src="https://github.com/blindner6/CEE6720_BIO6720/assets/144811435/7b252e0d-6efd-464c-ba50-502e7d3effa2">

I also tried to prepare these manifests with an actual tab instead of '\t'.

**Comment by princesspinamang** [comment]
Hi Madison, 

The \t is to let you know those entries should be tab-delimited. Your manifest.txt file should be formatted as such:

<img width="1437" alt="Screenshot 2024-03-13 at 2 24 32 AM" src="https://github.com/blindner6/CEE6720_BIO6720/assets/66684897/f69a9e7c-58b7-42a8-ba34-2f131dfa88b1">


Your working code is feeding the program one column for the input, when its looking for two. If you look at the documentation on GitHub for the .py script, you'll see that its using the tab space to split the file path from the sample names because those are 2 separate arguments. Later, your sample name will become the y-label for the plot. 

If you add those spaces to your files and make sure your conda/micromamba is active it will run properly.

**Comment by madisonflucas** [comment]
Hey! Sorry for the dumb question. The only reason I asked is because I had my manifests formatted that way the first time (or so I thought) and got the same error. BUT you're so right I tried it again and it ran perfectly. Thank you!

**Comment by bglindner** [comment]
Great! Thanks Princess. 

Not closing issues right now just to help with visibility.

**Comment by joverbey3** [comment]
I don't know why I'm still struggling with this. This is the error I keep running into:
![image](https://github.com/blindner6/CEE6720_BIO6720/assets/161337686/38035aaf-6da9-4ac8-945d-7b93f24a9e81)

Here are my manifests, and I double checked to make sure they are tab-deliminated: 
![image](https://github.com/blindner6/CEE6720_BIO6720/assets/161337686/0e0d7f23-cd70-4f53-8d0d-700f77f9f379)
![image](https://github.com/blindner6/CEE6720_BIO6720/assets/161337686/066cd14d-35e4-467a-8e53-d02c0b54b06b)

and the files in my directory are named accordingly
![image](https://github.com/blindner6/CEE6720_BIO6720/assets/161337686/bcbc12ef-ad35-4607-ad7d-895edbac2c40)
![image](https://github.com/blindner6/CEE6720_BIO6720/assets/161337686/829d0f72-5e55-4bec-afc8-7f0e7022b7aa)

**Comment by bglindner** [comment]
Hey Jorja,

Can you make sure that the whitespace in your manifests is a tab and not spaces? And make sure that the manifest with the .k2 files is going to `-k` and the bracken files are going to `-i`.

**Comment by joverbey3** [comment]
Hi blake. They are indeed tab deliminated, not spaces. My code is 
 
python Kraken-Bracken-plot.py -k kraken_manifest.tsv -i bracken_classes_manifest.tsv -o classes.pdf

where  kraken_manifest:
![image](https://github.com/blindner6/CEE6720_BIO6720/assets/161337686/31070579-7ac2-4beb-b64d-b6abcbf25fd4)
 Bracken Manifest:
![image](https://github.com/blindner6/CEE6720_BIO6720/assets/161337686/070d010c-7316-4ca1-bb4d-c62465f63023)

**Comment by joverbey3** [comment]
The error is unfortunately still the same

**Comment by bglindner** [comment]
Hey Jorja,

are you sure that your bracken files have results in them?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by joverbey3** [comment]
Hi Blake...After a few hours I realized that I was using the incorrect .k2 files. I'm dumb...it's fine we figured it out

**Comment by bglindner** [comment]
Persistence 🙏

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
